# Generated by Django 3.2.10 on 2022-02-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='hii', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
